name: Infrastructure

on:
  push:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  pull_request:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: ${{ (github.event_name == 'pull_request' && 'Validate') || 'Deploy' }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload Artifact (deploy)
        uses: actions/upload-artifact@v5
        with:
          path: deploy
          name: deploy
          retention-days: 1

      - name: Azure Login
        if: ${{ !contains(github.actor, '[bot]') }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Azure Resources
        if: ${{ !contains(github.actor, '[bot]') && github.event_name == 'pull_request' }}
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: 'validate'
          name: 'main-pr${{ github.event.number }}' # allows for concurrent validation
          scope: 'resourceGroup'
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: '${{ env.AZURE_RESOURCE_GROUP }}'
          template-file: '${{ github.workspace }}/deploy/main.bicep'

      - name: Deploy Azure Resources
        if: ${{ !contains(github.actor, '[bot]') && github.event_name != 'pull_request' }}
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: 'create'
          name: 'main'
          scope: 'resourceGroup'
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: '${{ env.AZURE_RESOURCE_GROUP }}'
          template-file: '${{ github.workspace }}/deploy/main.bicep'
