name: Web

on:
  workflow_dispatch:
  push:
    branches: [main]
    # tags: ['web**']
    paths:
      - 'apps/web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - '.github/workflows/web.yml'
      - 'packages/core/package.json'

permissions:
  contents: read
  pull-requests: write # required to write PR comment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # wait for previous runs to complete on main and tags
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

env:
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next.js telemetry
  TURBO_TELEMETRY_DISABLED: 1 # Disable Turbo telemetry

  GITHUB_SHA: ${{ github.sha }} # not discovered by default
  GITHUB_REF_NAME: ${{ github.ref_name }} # not discovered by default
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  Web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup turborepo caching
        uses: rharkor/caching-for-turbo@v2.3.2

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/apps/web'

      - name: Restore .next/cache
        id: cache-next-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-next-web-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-web

      - name: Build
        run: pnpm turbo build
        working-directory: '${{ github.workspace }}/apps/web'

      - name: Lint
        run: pnpm turbo lint
        working-directory: '${{ github.workspace }}/apps/web'

      - name: Test
        run: pnpm turbo test
        working-directory: '${{ github.workspace }}/apps/web'

      # Using Vercel for now (much faster) but we need the workflow to
      # validate builds especially for dependabot PRs

      - name: Save .next/cache
        if: always() && steps.cache-next-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ steps.cache-next-restore.outputs.cache-primary-key }}
